#solution to dotnet core app routing not working on Docker
FROM centos:7 AS base

# Add Microsoft package repository and install ASP.NET Core
RUN rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm \
    && yum install -y aspnetcore-runtime-6.0

# Ensure we listen on any IP Address 
ENV DOTNET_URLS=http://+:5000

WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /AtmMachine

# Copy everything
COPY . ./
# Restore as distinct layers
RUN dotnet restore
# Build and publish a release
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /AtmMachine
COPY --from=build-env /AtmMachine/out .
ENTRYPOINT ["dotnet", "AtmMachine.Web.dll"]