FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /AtmMachine

COPY *.csproj ./
#RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /AtmMachine
COPY --from=build-env /AtmMachine/out .
ENTRYPOINT ["dotnet", "AtmMachine.Web.dll"]
