// <auto-generated />
using AtmMachine.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AtmMachine.DAL.Migrations
{
    [DbContext(typeof(AtmMachineDbContext))]
    [Migration("20221020063425_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AtmMachine.Model.Account", b =>
                {
                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountNumber");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountNumber = "1122334455",
                            Pin = "1234"
                        },
                        new
                        {
                            AccountNumber = "1234567890",
                            Pin = "5432"
                        });
                });

            modelBuilder.Entity("AtmMachine.Model.AccountDetails", b =>
                {
                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AccountNumber");

                    b.ToTable("AccountDetails");

                    b.HasData(
                        new
                        {
                            AccountNumber = "1122334455",
                            Balance = 1234.56m
                        },
                        new
                        {
                            AccountNumber = "1234567890",
                            Balance = 5999.56m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
