// <auto-generated />
using AtmMachine.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AtmMachine.DAL.Migrations
{
    [DbContext(typeof(AtmMachineDbContext))]
    partial class AtmMachineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AtmMachine.Model.Account", b =>
                {
                    b.Property<string>("AccountNumber")
                        .HasColumnType("text");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AccountNumber");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountNumber = "1122334455",
                            Pin = "1234"
                        },
                        new
                        {
                            AccountNumber = "1234567890",
                            Pin = "5432"
                        });
                });

            modelBuilder.Entity("AtmMachine.Model.AccountDetails", b =>
                {
                    b.Property<string>("AccountNumber")
                        .HasColumnType("text");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.HasKey("AccountNumber");

                    b.ToTable("AccountDetails");

                    b.HasData(
                        new
                        {
                            AccountNumber = "1122334455",
                            Balance = 1234.56m
                        },
                        new
                        {
                            AccountNumber = "1234567890",
                            Balance = 5999.56m
                        });
                });

            modelBuilder.Entity("AtmMachine.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountNumber = "1122334455",
                            Name = "Luka",
                            Surname = "Komljenovic",
                            Username = "lkomljenovic"
                        },
                        new
                        {
                            Id = 2,
                            AccountNumber = "1234567890",
                            Name = "New",
                            Surname = "User",
                            Username = "nUser"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
